"""Layer 6 — Proactive Greeter.

Subscribes to perception-bus `face_recognized` events (and optionally
`face_detected` while Layer 4 face recognition is being wired up) and
pushes a context-aware greeting to the device when:

  - the recognised identity hasn't been greeted recently (cooldown),
  - per-day greeting cap hasn't been hit.

Time-of-day windows (morning / afternoon / evening) used to gate
whether a greeting fired at all; that gate was removed 2026-04-27 so
recognition reliably produces a greeting regardless of hour. The
time-of-day label is still derived from current hour for natural
phrasing in the prompt and template fallback.

The greeting is generated by the same LLM as voice turns (via an
injected `llm_client`) using `summarize_for_prompt(events, person=name)`
to pull only that person's calendar items for today. A short template
fallback fires whenever the LLM is unreachable, so the greeter never
silently no-ops because of a transient upstream failure.

All external calls (LLM, TTS push, calendar lookup, state I/O) are
wrapped — a greeter failure must never break the voice path or the
perception bus.

State
-----
Per-person greet log is persisted at `GREETER_STATE_PATH`
(default `~/.zeroclaw/greeter_state.json`) so a bridge restart doesn't
re-greet everyone in the house. Atomic write (temp + rename); on JSON
parse failure we start fresh rather than crash.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Awaitable, Callable, Optional
from zoneinfo import ZoneInfo

log = logging.getLogger("stackchan-bridge.proactive_greeter")


# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------


def _env_bool(key: str, default: bool) -> bool:
    raw = os.environ.get(key)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


def _env_float(key: str, default: float) -> float:
    try:
        return float(os.environ.get(key, default))
    except (TypeError, ValueError):
        return default


def _env_int(key: str, default: int) -> int:
    try:
        return int(os.environ.get(key, default))
    except (TypeError, ValueError):
        return default


# ---------------------------------------------------------------------------
# Greeter
# ---------------------------------------------------------------------------


class ProactiveGreeter:
    """Subscribes to perception events and emits proactive greetings.

    Dependencies are injected so the class is unit-testable without
    needing to spin up the FastAPI app. Concretely, ``perception_bus``
    is any object with ``subscribe()`` / ``unsubscribe(q)`` returning
    an ``asyncio.Queue``.

    Parameters
    ----------
    perception_bus :
        Object exposing ``subscribe()`` -> ``asyncio.Queue`` and
        ``unsubscribe(q)``. In production this wraps the in-process
        listeners list in ``bridge.py``.
    llm_client :
        Async callable ``(prompt: str) -> str`` that returns a single
        completion. May raise — we always have a template fallback.
    calendar_cache :
        Object with ``get_events()`` and ``summarize_for_prompt(events,
        person, include_household)``. Either may raise; we degrade to
        no calendar context.
    tts_pusher :
        Async callable ``(device_id: str, text: str) -> Awaitable``
        that delivers the greeting to the device. Errors are logged
        but never propagated.
    kid_mode_provider :
        Callable returning the current kid-mode flag (bool). Sampled
        every greeting so a dashboard flip takes effect without a restart.
    """

    DEFAULT_STATE_PATH = "~/.zeroclaw/greeter_state.json"

    def __init__(
        self,
        perception_bus: Any,
        llm_client: Callable[[str], Awaitable[str]],
        calendar_cache: Any,
        tts_pusher: Callable[[str, str], Awaitable[Any]],
        kid_mode_provider: Callable[[], bool],
        *,
        household_registry: Any = None,
        turn_logger: Optional[Callable[..., None]] = None,
        clock: Callable[[], float] = time.time,
        tz: Optional[ZoneInfo] = None,
    ) -> None:
        self._bus = perception_bus
        self._llm = llm_client
        self._calendar = calendar_cache
        self._tts = tts_pusher
        self._kid_mode = kid_mode_provider
        # Optional. When supplied, every greeting (success or push-error)
        # is mirrored as a synthetic conversation turn with channel="greeter"
        # so the dashboard's unified Activity feed surfaces it alongside
        # voice turns. Inject `_convo_log.log_turn` from bridge.py.
        self._turn_logger = turn_logger
        # Optional. When supplied, we enrich greetings with display name,
        # personality and birthday awareness. None == legacy behaviour
        # (raw identity string). See bridge/household.py.
        self._household = household_registry
        self._clock = clock
        tz_name = os.environ.get("TZ", "Australia/Brisbane")
        self._tz = tz or ZoneInfo(tz_name)

        # Config — sampled at construction; restart to change.
        self.enabled = _env_bool("GREETER_ENABLED", True)
        self.use_face_detected = _env_bool(
            "GREETER_USE_FACE_DETECTED", False)
        self.greet_unknown = _env_bool("GREETER_GREET_UNKNOWN", False)
        self.cooldown_seconds = _env_float(
            "GREETER_COOLDOWN_HOURS", 4.0) * 3600.0
        self.per_day_max = _env_int("GREETER_PER_DAY_MAX", 3)
        self.greeting_max_words = _env_int("GREETER_GREETING_MAX_WORDS", 15)

        state_path_raw = os.environ.get(
            "GREETER_STATE_PATH", self.DEFAULT_STATE_PATH)
        self._state_path = Path(state_path_raw).expanduser()

        # In-memory greet log: {date_str: {identity: {"count": N, "last_ts": float}}}
        self._state: dict[str, dict[str, dict[str, Any]]] = self._load_state()

        self._task: Optional[asyncio.Task] = None
        self._stopped = False

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def start(self) -> None:
        if not self.enabled:
            log.info("ProactiveGreeter disabled (GREETER_ENABLED=false)")
            return
        if self._task is not None and not self._task.done():
            log.warning("ProactiveGreeter.start() called twice; ignoring")
            return
        self._stopped = False
        self._task = asyncio.create_task(self._run())
        log.info(
            "ProactiveGreeter started "
            "(use_face_detected=%s greet_unknown=%s cooldown_s=%.0f "
            "per_day_max=%d state=%s)",
            self.use_face_detected, self.greet_unknown,
            self.cooldown_seconds, self.per_day_max, self._state_path,
        )

    async def stop(self) -> None:
        self._stopped = True
        if self._task is None:
            return
        self._task.cancel()
        try:
            await self._task
        except (asyncio.CancelledError, Exception):
            pass
        self._task = None

    # ------------------------------------------------------------------
    # Event loop
    # ------------------------------------------------------------------
    async def _run(self) -> None:
        try:
            q = self._bus.subscribe()
        except Exception:
            log.exception("ProactiveGreeter: bus.subscribe() failed")
            return
        try:
            while not self._stopped:
                event = await q.get()
                try:
                    await self._handle(event)
                except Exception:
                    # Defensive — never let a bad event kill the loop.
                    log.exception(
                        "ProactiveGreeter: handler raised (event=%s)",
                        event.get("name") if isinstance(event, dict) else "?",
                    )
        except asyncio.CancelledError:
            log.info("ProactiveGreeter cancelled")
            raise
        finally:
            try:
                self._bus.unsubscribe(q)
            except Exception:
                log.debug("ProactiveGreeter: unsubscribe raised", exc_info=True)

    async def _handle(self, event: dict) -> None:
        """Dispatch loop hook used by `_run`. Public-ish for tests."""
        if not isinstance(event, dict):
            return
        name = event.get("name") or ""
        if name == "face_recognized":
            return await self._on_face_recognized(event)
        if name == "face_detected" and self.use_face_detected:
            # Synthesise a face_recognized-style payload with identity
            # left as "unknown" so the unknown-face branch handles it.
            return await self._on_face_recognized({
                **event,
                "data": {**(event.get("data") or {}), "identity": "unknown"},
            })

    async def _on_face_recognized(self, event: dict) -> None:
        """Main handler. Called for both `face_recognized` events and
        (when enabled) `face_detected` events promoted to unknown."""
        device_id = event.get("device_id") or ""
        if not device_id or device_id == "unknown":
            return
        data = event.get("data") or {}
        identity = (data.get("identity") or "").strip() or "unknown"

        # Time-of-day label is now informational only (used to phrase the
        # greeting); it never gates whether a greeting fires.
        time_of_day = self._current_window()

        t0 = self._clock()

        # Unknown branch.
        if identity == "unknown":
            if not self.greet_unknown:
                log.debug(
                    "greeter: unknown face skipped (GREETER_GREET_UNKNOWN=false)"
                )
                return
            if not self._take_slot(identity, event_ts=event.get("ts")):
                return
            text = self._sandwich(
                "Hello! I don't think we've met.", window=time_of_day,
            )
            await self._safe_push(
                device_id, text, t0=t0,
                request_text=f"face:{identity}",
            )
            return

        # Known identity.
        if not self._take_slot(identity, event_ts=event.get("ts")):
            return

        greeting = await self._generate_greeting(
            identity=identity, window=time_of_day,
        )
        text = self._sandwich(greeting, window=time_of_day)
        await self._safe_push(
            device_id, text, t0=t0,
            request_text=f"face:{identity}",
        )

    # ------------------------------------------------------------------
    # Time-of-day label
    # ------------------------------------------------------------------
    def _current_window(self) -> str:
        """Return a time-of-day label always — formerly gated greeting
        on membership in configured windows; that gate was removed
        2026-04-27 so a recognised face produces a greeting at any
        hour, subject to cooldown and per-day cap. The label is still
        passed through to the LLM prompt and template fallback for
        natural phrasing ("Good morning, Brett!" vs "Good evening, …")."""
        now = datetime.fromtimestamp(self._clock(), tz=self._tz)
        hour = now.hour
        if 5 <= hour < 12:
            return "morning"
        if 12 <= hour < 17:
            return "afternoon"
        if 17 <= hour < 21:
            return "evening"
        return "night"

    # ------------------------------------------------------------------
    # Cooldown / per-day cap
    # ------------------------------------------------------------------
    def _today_key(self) -> str:
        return datetime.fromtimestamp(self._clock(), tz=self._tz).strftime("%Y-%m-%d")

    def _take_slot(self, identity: str, *, event_ts: Optional[float]) -> bool:
        """Return True iff this identity is allowed to be greeted now;
        records the slot if so. Combines cooldown + per-day cap."""
        now = float(event_ts) if event_ts else self._clock()
        today = self._today_key()
        # Garbage-collect old days so the file doesn't grow unbounded.
        if today not in self._state:
            self._state = {today: self._state.get(today, {})}
        bucket = self._state.setdefault(today, {})
        slot = bucket.get(identity, {"count": 0, "last_ts": 0.0})
        if slot["count"] >= self.per_day_max:
            log.info(
                "greeter: per-day cap reached for identity=%s (count=%d)",
                identity, slot["count"],
            )
            return False
        last_ts = float(slot.get("last_ts") or 0.0)
        # last_ts == 0 is the sentinel meaning "never greeted" — don't
        # apply the cooldown to a first greeting, only to repeats.
        if last_ts > 0.0 and now - last_ts < self.cooldown_seconds:
            log.info(
                "greeter: cooldown active for identity=%s "
                "(%.0fs since last)",
                identity, now - last_ts,
            )
            return False
        slot["count"] = int(slot["count"]) + 1
        slot["last_ts"] = now
        bucket[identity] = slot
        self._save_state()
        return True

    # ------------------------------------------------------------------
    # Greeting generation
    # ------------------------------------------------------------------
    async def _generate_greeting(
        self, *, identity: str, window: str,
    ) -> str:
        """Build the greeting text. LLM call with template fallback."""
        events_summary: list[str] = []
        try:
            events = self._calendar.get_events()
            events_summary = self._calendar.summarize_for_prompt(
                events, person=identity, include_household=True,
            ) or []
        except Exception:
            log.warning(
                "greeter: calendar lookup failed for %s; continuing without",
                identity, exc_info=True,
            )

        prompt = self._build_prompt(
            identity=identity, window=window, events=events_summary,
        )
        try:
            text = await self._llm(prompt)
            cleaned = self._post_process(text or "")
            if cleaned:
                return cleaned
            log.info("greeter: LLM returned empty; using template fallback")
        except Exception:
            log.warning(
                "greeter: LLM call failed; using template fallback",
                exc_info=True,
            )
        return self._template_fallback(identity=identity, window=window)

    def _build_prompt(
        self, *, identity: str, window: str, events: list[str],
    ) -> str:
        bullet_block = (
            "\n".join(f"- {e}" for e in events) if events else "(none)"
        )
        max_words = self.greeting_max_words

        # Registry enrichment — display name, compact persona, and
        # birthday awareness. Fall through to raw identity when absent.
        person = self._lookup_person(identity)
        addressee = person.display_name if person else identity
        persona_line = ""
        birthday_line = ""
        if person is not None:
            descr = person.compact_description(max_chars=180)
            if descr:
                persona_line = f"About {addressee}: {descr}\n"
            days = person.days_until_birthday()
            if days is not None:
                if days == 0:
                    birthday_line = (
                        f"It is {addressee}'s birthday today — "
                        f"a warm acknowledgement is welcome.\n"
                    )
                elif 1 <= days <= 7:
                    birthday_line = (
                        f"{addressee}'s birthday is in {days} day"
                        f"{'s' if days != 1 else ''} — you may mention "
                        f"it lightly if it fits.\n"
                    )

        return (
            f"You are Dotty, a friendly home robot. {addressee} just "
            f"walked into the room. The time of day is {window}.\n"
            f"{persona_line}"
            f"{birthday_line}"
            f"Today's calendar items relevant to {addressee}:\n"
            f"{bullet_block}\n\n"
            f"Write a single short, warm spoken greeting addressed to "
            f"{addressee}. If a calendar item is highly relevant to the "
            f"current time-of-day window, you may mention it naturally — "
            f"otherwise just greet them. "
            f"Hard rules: ENGLISH ONLY. {max_words} words or fewer. "
            f"One sentence. No emoji, no Markdown, no lists."
        )

    def _lookup_person(self, identity: str) -> Any:
        """Look up a person in the registry. Returns None when no
        registry is wired or identity is unknown to it. Defensive — a
        registry hiccup must never break the greeter."""
        if not self._household or not identity or identity == "unknown":
            return None
        try:
            return self._household.get(identity)
        except Exception:
            log.debug(
                "greeter: household registry lookup failed for %s",
                identity, exc_info=True,
            )
            return None

    @staticmethod
    def _post_process(text: str) -> str:
        cleaned = " ".join(text.strip().split())
        # Strip wrapping quotes the LLM likes to add.
        if len(cleaned) >= 2 and cleaned[0] in "\"'" and cleaned[-1] in "\"'":
            cleaned = cleaned[1:-1].strip()
        return cleaned

    def _template_fallback(self, *, identity: str, window: str) -> str:
        person = self._lookup_person(identity)
        addressee = person.display_name if person else identity
        return f"Good {window}, {addressee}!"

    # ------------------------------------------------------------------
    # Kid-safe sandwich
    # ------------------------------------------------------------------
    def _sandwich(self, text: str, *, window: str) -> str:
        """Wrap the greeting with the same safety contract voice turns
        get. We deliberately keep this lightweight here because the
        greeting is not user-driven — it's server-generated and already
        constrained by the prompt above. The wrapper exists primarily
        to (a) keep the surface uniform and (b) ensure kid-mode rules
        propagate if the greeting later flows through any general-purpose
        path that re-interprets it."""
        # Local import to avoid a circular dependency on bridge.py — the
        # actual VOICE_TURN_PREFIX/SUFFIX constants live in bridge.py and
        # are not needed for the *output* text we send to TTS, which must
        # be plain spoken English. The sandwich is applied conceptually
        # by the prompt, and the output here is what the device will
        # actually speak.
        try:
            kid = bool(self._kid_mode())
        except Exception:
            kid = True  # Default to safer when in doubt.
        if kid:
            # Defensive scrub — strip stray emoji prefix patterns the LLM
            # sometimes adds despite the prompt telling it not to.
            for ch in ("😊", "😆", "😢", "😮", "🤔", "😠", "😐", "😍", "😴"):
                if text.startswith(ch):
                    text = text[len(ch):].lstrip()
                    break
        return text

    # ------------------------------------------------------------------
    # TTS push
    # ------------------------------------------------------------------
    async def _safe_push(
        self,
        device_id: str,
        text: str,
        *,
        t0: Optional[float] = None,
        request_text: str = "",
    ) -> None:
        if not text:
            return
        err: Optional[str] = None
        try:
            await self._tts(device_id, text)
            log.info(
                "greeter: pushed greeting device=%s text=%r", device_id, text,
            )
        except Exception as exc:
            log.exception(
                "greeter: tts_pusher raised (device=%s)", device_id,
            )
            err = repr(exc)[:200]
        if self._turn_logger is not None:
            latency_ms = (
                (self._clock() - t0) * 1000.0 if t0 is not None else 0.0
            )
            try:
                self._turn_logger(
                    channel="greeter",
                    session_id="",
                    request_text=request_text,
                    response_text=text,
                    latency_ms=latency_ms,
                    error=err,
                )
            except Exception:
                log.debug(
                    "greeter: turn_logger raised", exc_info=True,
                )

    # ------------------------------------------------------------------
    # State persistence
    # ------------------------------------------------------------------
    def _load_state(self) -> dict[str, dict[str, dict[str, Any]]]:
        try:
            if not self._state_path.exists():
                return {}
            raw = self._state_path.read_text(encoding="utf-8")
            data = json.loads(raw)
            if not isinstance(data, dict):
                log.warning("greeter: state file not a dict; starting fresh")
                return {}
            # Coerce shape — accept anything saved by an older version.
            out: dict[str, dict[str, dict[str, Any]]] = {}
            for day, bucket in data.items():
                if not isinstance(bucket, dict):
                    continue
                inner: dict[str, dict[str, Any]] = {}
                for identity, slot in bucket.items():
                    if isinstance(slot, dict):
                        inner[identity] = {
                            "count": int(slot.get("count") or 0),
                            "last_ts": float(slot.get("last_ts") or 0.0),
                        }
                out[str(day)] = inner
            return out
        except (OSError, json.JSONDecodeError, ValueError):
            log.warning(
                "greeter: state file unreadable; starting fresh",
                exc_info=True,
            )
            return {}

    def _save_state(self) -> None:
        try:
            self._state_path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self._state_path.with_suffix(
                self._state_path.suffix + ".tmp"
            )
            tmp.write_text(
                json.dumps(self._state, separators=(",", ":")),
                encoding="utf-8",
            )
            os.replace(tmp, self._state_path)
        except OSError:
            log.warning(
                "greeter: failed to persist state to %s",
                self._state_path, exc_info=True,
            )


__all__ = ["ProactiveGreeter"]
