"""Prepare/build the pinned commercial StackChan firmware; never flashes a device."""
from __future__ import annotations
import argparse
import ipaddress
import json
import os
from pathlib import Path
import re
import subprocess
import sys

FACTORY_REV = '1b5765599fba8aaad1811d9a79358ccc7051f5f3'
FACTORY_URL = 'https://github.com/m5stack/StackChan.git'
ROOT = Path(__file__).resolve().parent


def run(args, cwd=None, capture=False):
    return subprocess.run([str(a) for a in args], cwd=cwd, check=True,
                          text=True, stdout=subprocess.PIPE if capture else None)


def endpoint_header(host, port=8000):
    try:
        ip = ipaddress.IPv4Address(host)
    except ipaddress.AddressValueError as exc:
        raise ValueError('Use your PC private LAN IPv4 address.') from exc
    networks = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
    if not any(ip in ipaddress.ip_network(n) for n in networks) or not 1 <= port <= 65535:
        raise ValueError('Use your PC private LAN IPv4 address and a valid port.')
    return ('// Generated by Stakia build_factory.py\n#pragma once\n'
            f'#define STAKIA_WEBSOCKET_URL "ws://{ip}:{port}/xiaozhi/v1/"\n')


def ensure_patch(repo, patch):
    applied = subprocess.run(['git', '-C', str(repo), 'apply', '--reverse', '--check', str(patch)],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if applied.returncode == 0:
        return
    run(['git', '-C', repo, 'apply', '--check', patch])
    run(['git', '-C', repo, 'apply', patch])


def prepare_source(source, eyes):
    if not source.exists():
        run(['git', 'clone', '--no-checkout', FACTORY_URL, source])
        run(['git', '-C', source, 'checkout', '--detach', FACTORY_REV])
    actual = run(['git', '-C', source, 'rev-parse', 'HEAD'], capture=True).stdout.strip()
    if actual != FACTORY_REV:
        raise ValueError(f'Source is {actual}; expected {FACTORY_REV}. Use a separate checkout.')
    ensure_patch(source, ROOT / 'stakia' / 'local-only-factory.patch')
    if eyes == 'stakia':
        ensure_patch(source, ROOT / 'stakia' / 'expressive-eyes.patch')
    else:
        changes = run(['git', '-C', source, 'status', '--porcelain', '--',
                       'firmware/main/stackchan/avatar/skins/default'], capture=True).stdout
        if changes.strip():
            raise ValueError('Stock baseline requested but eye sources are modified. Use a clean separate source directory.')
    return source / 'firmware'


def fetch_dependencies(fw):
    # Unlike the upstream helper, stop if a required patch cannot be applied.
    for item in json.loads((fw / 'repos.json').read_text()):
        dest = fw / item['path']
        if not dest.exists():
            run(['git', 'clone', item['url'], dest])
        ref = item.get('branch')
        expected = run(['git', '-C', dest, 'rev-parse', ref], capture=True).stdout.strip()
        actual = run(['git', '-C', dest, 'rev-parse', 'HEAD'], capture=True).stdout.strip()
        if actual != expected:
            if run(['git', '-C', dest, 'status', '--porcelain'], capture=True).stdout.strip():
                raise ValueError(f'Dirty dependency at a different revision: {dest}')
            run(['git', '-C', dest, 'checkout', '--detach', ref])
        if item.get('with_submodules'):
            run(['git', '-C', dest, 'submodule', 'update', '--init', '--recursive'])
        if item.get('patch'):
            ensure_patch(dest, fw / item['patch'])


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--source', type=Path, default=ROOT / 'StackChan')
    ap.add_argument('--eyes', choices=['stock', 'stakia'], default='stakia')
    ap.add_argument('--server-host', required=True, help='Your PC private LAN IPv4 address. No vendor bootstrap is used.')
    ap.add_argument('--server-port', type=int, default=8000)
    ap.add_argument('--prepare-only', action='store_true', help='Prepare pinned source/eye patch; no IDF or dependency download.')
    args = ap.parse_args()
    header = endpoint_header(args.server_host, args.server_port)
    source = args.source.resolve()
    fw = prepare_source(source, args.eyes)
    # The generated header is found through the factory main include path.
    (fw / 'main' / 'stakia_endpoint.h').write_text(header, encoding='utf-8')
    if args.prepare_only:
        print(f'Prepared source: {fw}. No firmware compiled or flashed.')
        return
    idf_root = os.environ.get('IDF_PATH')
    if not idf_root or not (Path(idf_root) / 'tools' / 'idf.py').is_file():
        raise ValueError('Open your installed ESP-IDF terminal first. IDF_PATH must point to ESP-IDF 5.5.4.')
    idf = [sys.executable, str(Path(idf_root) / 'tools' / 'idf.py')]
    version = run(idf + ['--version'], capture=True).stdout.strip()
    if not re.search(r'\bv5\.5\.4(?:\s|$)', version):
        raise ValueError(f'Expected ESP-IDF v5.5.4; found {version}. This source is pinned to that toolchain.')
    fetch_dependencies(fw)
    ensure_patch(fw / 'xiaozhi-esp32', ROOT / 'stakia' / 'local-only-xiaozhi.patch')
    # Isolate sdkconfig from previous generic firmware and build runs.
    build = fw / ('build-' + args.eyes)
    build.mkdir(exist_ok=True)
    run(idf + ['-B', build, '-D', f'SDKCONFIG={build / "sdkconfig"}', 'build'], cwd=fw)
    print(f'Built {args.eyes} firmware in {build}. Nothing flashed.')
    print('Verify the USB port, then follow firmware/STAKIA-BUILD.md to flash.')

if __name__ == '__main__':
    try:
        main()
    except (ValueError, subprocess.CalledProcessError) as exc:
        print(f'Build stopped: {exc}', file=sys.stderr)
        sys.exit(1)
